# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6E5-ltXo8wHrytl_FIME9BwRb70o-Le
"""

#list1 = [1,2,3]
#print(list1);

list2 = [i for i in range(10)]
print(list2);
list3 = [[j for j in range(6)] for i in range(5)]
print(list3);
list4 = [[3*j+ i for j in range(3)] for i in range(3)]
print(list4);